package io.browserservice.api.openapi;

import static org.assertj.core.api.Assertions.assertThat;

import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;
import org.springframework.test.web.servlet.result.MockMvcResultMatchers;
import org.yaml.snakeyaml.Yaml;

/**
 * Asserts that the OpenAPI spec generated by SpringDoc declares the {@code X-Caller-Id} header as a
 * required parameter on every operation under {@code /v1/}, and does <em>not</em> declare it on
 * unauthenticated probes ({@code /healthz}, {@code /readyz}). This guards the contract directly,
 * independent of the snapshot in {@code openapi/generated.yaml} maintained by {@link
 * SpecExportTest}.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.MOCK)
@AutoConfigureMockMvc
@org.springframework.test.context.ActiveProfiles("test")
@TestPropertySource(
    properties = {
      "browserservice.selenium.urls=http://localhost:4444/wd/hub",
      "browserservice.appium.urls=",
      "browserservice.browserstack.enabled=false"
    })
class CallerIdSpecTest {

  private static final String CALLER_HEADER = "X-Caller-Id";

  @Autowired private MockMvc mvc;

  @Test
  @SuppressWarnings("unchecked")
  void everyV1OperationRequiresCallerIdHeader() throws Exception {
    Map<String, Object> spec = fetchSpec();
    Map<String, Object> paths = (Map<String, Object>) spec.get("paths");
    assertThat(paths).as("spec.paths").isNotEmpty();

    int v1Operations = 0;
    for (Map.Entry<String, Object> entry : paths.entrySet()) {
      String path = entry.getKey();
      if (!path.startsWith("/v1/")) {
        continue;
      }
      Map<String, Object> pathItem = (Map<String, Object>) entry.getValue();
      for (Map.Entry<String, Object> opEntry : pathItem.entrySet()) {
        if (!HTTP_METHODS.contains(opEntry.getKey())) {
          continue;
        }
        v1Operations++;
        Map<String, Object> op = (Map<String, Object>) opEntry.getValue();
        Map<String, Object> param =
            findHeaderParameter(op, CALLER_HEADER)
                .orElseThrow(
                    () ->
                        new AssertionError(
                            "missing X-Caller-Id parameter on " + opEntry.getKey() + " " + path));
        assertThat(param.get("required"))
            .as("X-Caller-Id required on %s %s", opEntry.getKey(), path)
            .isEqualTo(Boolean.TRUE);
      }
    }
    assertThat(v1Operations).as("number of /v1/ operations inspected").isPositive();
  }

  @Test
  @SuppressWarnings("unchecked")
  void healthAndReadinessProbesDoNotRequireCallerIdHeader() throws Exception {
    Map<String, Object> spec = fetchSpec();
    Map<String, Object> paths = (Map<String, Object>) spec.get("paths");

    for (String probePath : List.of("/healthz", "/readyz")) {
      Map<String, Object> pathItem = (Map<String, Object>) paths.get(probePath);
      assertThat(pathItem).as("path %s present in spec", probePath).isNotNull();
      for (Map.Entry<String, Object> opEntry : pathItem.entrySet()) {
        if (!HTTP_METHODS.contains(opEntry.getKey())) {
          continue;
        }
        Map<String, Object> op = (Map<String, Object>) opEntry.getValue();
        assertThat(findHeaderParameter(op, CALLER_HEADER))
            .as("X-Caller-Id should not appear on %s %s", opEntry.getKey(), probePath)
            .isEmpty();
      }
    }
  }

  @SuppressWarnings("unchecked")
  private Map<String, Object> fetchSpec() throws Exception {
    String body =
        mvc.perform(MockMvcRequestBuilders.get("/v3/api-docs.yaml"))
            .andExpect(MockMvcResultMatchers.status().isOk())
            .andReturn()
            .getResponse()
            .getContentAsString(StandardCharsets.UTF_8);
    return (Map<String, Object>) new Yaml().load(body);
  }

  @SuppressWarnings("unchecked")
  private static java.util.Optional<Map<String, Object>> findHeaderParameter(
      Map<String, Object> operation, String name) {
    Object params = operation.get("parameters");
    if (!(params instanceof List<?> list)) {
      return java.util.Optional.empty();
    }
    for (Object raw : list) {
      if (!(raw instanceof Map<?, ?> map)) {
        continue;
      }
      Map<String, Object> param = (Map<String, Object>) map;
      if ("header".equals(param.get("in")) && name.equals(param.get("name"))) {
        return java.util.Optional.of(param);
      }
    }
    return java.util.Optional.empty();
  }

  private static final java.util.Set<String> HTTP_METHODS =
      java.util.Set.of("get", "put", "post", "delete", "patch", "head", "options", "trace");
}
